# Name: auto deploy
name: Auto deploy

# trigger
on:
  push:
    branches:
      - "main"

# build, deploy job definition
jobs:
  build:
    runs-on: ubuntu-latest # runner os
    name: Build docker image and push to ghcr.io # job name
    steps:
      # github repository checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # setup docker buildx
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
      # cache docker layers
      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.VERSION }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      # ghcr.io login and build
      - name: Login with ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      # build docker image
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/usagi:latest
      - name: Invoke auto deploy webhook
        run: |
          curl -X POST ${{ secrets.WEBHOOK_URL }}